export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const SAVE_ITEM_SUCCESS = "SAVE_ITEM_SUCCESS";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";

export const LOAD_PARTNERS_SUCCESS = "LOAD_PARTNERS_SUCCESS";
export const SAVE_PARTNER_SUCCESS = "SAVE_PARTNER_SUCCESS";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
